- name: Setup NGINX and deploy Yii2 Docker container on EC2
  hosts: web
  become: true
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Apache is stopped
      systemd:
        name: apache2
        state: stopped
        enabled: no

    - name: Install required packages for Docker
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present
        filename: docker
    
    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Pull Yii2 Docker image from Docker Hub
      shell: docker pull utkarshsathe/yii2-app:latest

    - name: Remove existing Yii2 Docker container (if any)
      shell: docker rm -f yii2-app || true

    - name: Run Yii2 Docker container
      shell: docker run -d -p 8080:80 --name yii2-app utkarshsathe/yii2-app:latest

    - name: Copy NGINX reverse proxy config
      copy:
        dest: /etc/nginx/sites-available/yii2
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://localhost:8080;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Enable the NGINX site
      file:
        src: /etc/nginx/sites-available/yii2
        dest: /etc/nginx/sites-enabled/yii2
        state: link
        force: yes

    - name: Remove default site if present
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart NGINX
      systemd:
        name: nginx
        state: restarted

# - name: Setup NGINX on EC2
#   hosts: web
#   become: true
#   tasks:
#     - name: Install NGINX
#       apt:
#         name: nginx
#         state: present
#         update_cache: yes

#     - name: Copy NGINX site config
#       copy:
#         src: ./yii2-app-basic
#         dest: /var/www/html/

#     - name: Enable the NGINX site
#       file:
#         src: /etc/nginx/sites-available/yii2
#         dest: /etc/nginx/sites-enabled/yii2
#         state: link

#     - name: Ensure Apache is stopped
#       systemd:
#         name: apache2
#         state: stopped
#         enabled: no

#     - name: Restart NGINX
#       systemd:
#         name: nginx
#         state: restarted
