name: Deploy to EC2 with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Docker username
      run: |
        echo "Docker username: ${{ secrets.DOCKER_USERNAME }}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t utkarshsathe/yii2-app:latest .

    - name: Push Docker image
      run: |
        docker push utkarshsathe/yii2-app:latest

    - name: Set up Python and install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Add SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem

    - name: Add EC2 host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 13.218.122.242 >> ~/.ssh/known_hosts

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory.ini playbook.yml --private-key ec2_key.pem
