name: Deploy to EC2 with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python and install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Add SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory.ini playbook.yml --private-key ec2_key.pem
